/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateK24ConfigInput = {
  id?: string | null,
  name?: string | null,
  category: Category,
  topic: string,
  query: string,
  enabled: boolean,
  file_path?: string | null,
  last_updated?: string | null,
  count: number,
  since_id?: number | null,
};

export enum Category {
  Text = "Text",
  Image = "Image",
  Video = "Video",
  News = "News",
}


export type ModelK24ConfigConditionInput = {
  name?: ModelStringInput | null,
  category?: ModelCategoryInput | null,
  topic?: ModelStringInput | null,
  query?: ModelStringInput | null,
  enabled?: ModelBooleanInput | null,
  file_path?: ModelStringInput | null,
  last_updated?: ModelStringInput | null,
  count?: ModelIntInput | null,
  since_id?: ModelFloatInput | null,
  and?: Array< ModelK24ConfigConditionInput | null > | null,
  or?: Array< ModelK24ConfigConditionInput | null > | null,
  not?: ModelK24ConfigConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelCategoryInput = {
  eq?: Category | null,
  ne?: Category | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdateK24ConfigInput = {
  id: string,
  name?: string | null,
  category?: Category | null,
  topic?: string | null,
  query?: string | null,
  enabled?: boolean | null,
  file_path?: string | null,
  last_updated?: string | null,
  count?: number | null,
  since_id?: number | null,
};

export type DeleteK24ConfigInput = {
  id?: string | null,
};

export type CreateK24TweetsInput = {
  id?: string | null,
  Id: string,
  text: string,
  category: Category,
  tweet_created_at: string,
  tweet_date: string,
  user_name: string,
  topic: string,
  enabled?: boolean | null,
  file_path: string,
  last_updated?: string | null,
  duration_millis?: number | null,
  favorite_count?: number | null,
  followers_count?: number | null,
  hashtags?: Array< string | null > | null,
  location?: string | null,
  media_url_https?: string | null,
  reply_count?: number | null,
  retweet_count?: number | null,
  retweeted?: boolean | null,
  row_timestamp?: string | null,
  screen_name?: string | null,
  source_device?: string | null,
  truncated?: boolean | null,
  user_status_count?: number | null,
  video_url?: string | null,
  configID: string,
};

export type ModelK24TweetsConditionInput = {
  Id?: ModelIDInput | null,
  text?: ModelStringInput | null,
  category?: ModelCategoryInput | null,
  tweet_created_at?: ModelStringInput | null,
  tweet_date?: ModelStringInput | null,
  user_name?: ModelStringInput | null,
  topic?: ModelStringInput | null,
  enabled?: ModelBooleanInput | null,
  file_path?: ModelStringInput | null,
  last_updated?: ModelStringInput | null,
  duration_millis?: ModelIntInput | null,
  favorite_count?: ModelIntInput | null,
  followers_count?: ModelFloatInput | null,
  hashtags?: ModelStringInput | null,
  location?: ModelStringInput | null,
  media_url_https?: ModelStringInput | null,
  reply_count?: ModelIntInput | null,
  retweet_count?: ModelIntInput | null,
  retweeted?: ModelBooleanInput | null,
  row_timestamp?: ModelStringInput | null,
  screen_name?: ModelStringInput | null,
  source_device?: ModelStringInput | null,
  truncated?: ModelBooleanInput | null,
  user_status_count?: ModelIntInput | null,
  video_url?: ModelStringInput | null,
  configID?: ModelIDInput | null,
  and?: Array< ModelK24TweetsConditionInput | null > | null,
  or?: Array< ModelK24TweetsConditionInput | null > | null,
  not?: ModelK24TweetsConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateK24TweetsInput = {
  Id?: string | null,
  text?: string | null,
  category?: Category | null,
  tweet_created_at?: string | null,
  tweet_date?: string | null,
  user_name?: string | null,
  topic?: string | null,
  enabled?: boolean | null,
  file_path?: string | null,
  last_updated?: string | null,
  duration_millis?: number | null,
  favorite_count?: number | null,
  followers_count?: number | null,
  hashtags?: Array< string | null > | null,
  location?: string | null,
  media_url_https?: string | null,
  reply_count?: number | null,
  retweet_count?: number | null,
  retweeted?: boolean | null,
  row_timestamp?: string | null,
  screen_name?: string | null,
  source_device?: string | null,
  truncated?: boolean | null,
  user_status_count?: number | null,
  video_url?: string | null,
  configID?: string | null,
};

export type DeleteK24TweetsInput = {
  id?: string | null,
};

export type ModelK24ConfigFilterInput = {
  id?: ModelIDInput | null,
  name?: ModelStringInput | null,
  category?: ModelCategoryInput | null,
  topic?: ModelStringInput | null,
  query?: ModelStringInput | null,
  enabled?: ModelBooleanInput | null,
  file_path?: ModelStringInput | null,
  last_updated?: ModelStringInput | null,
  count?: ModelIntInput | null,
  since_id?: ModelFloatInput | null,
  and?: Array< ModelK24ConfigFilterInput | null > | null,
  or?: Array< ModelK24ConfigFilterInput | null > | null,
  not?: ModelK24ConfigFilterInput | null,
};

export type ModelK24TweetsFilterInput = {
  Id?: ModelIDInput | null,
  text?: ModelStringInput | null,
  category?: ModelCategoryInput | null,
  tweet_created_at?: ModelStringInput | null,
  tweet_date?: ModelStringInput | null,
  user_name?: ModelStringInput | null,
  topic?: ModelStringInput | null,
  enabled?: ModelBooleanInput | null,
  file_path?: ModelStringInput | null,
  last_updated?: ModelStringInput | null,
  duration_millis?: ModelIntInput | null,
  favorite_count?: ModelIntInput | null,
  followers_count?: ModelFloatInput | null,
  hashtags?: ModelStringInput | null,
  location?: ModelStringInput | null,
  media_url_https?: ModelStringInput | null,
  reply_count?: ModelIntInput | null,
  retweet_count?: ModelIntInput | null,
  retweeted?: ModelBooleanInput | null,
  row_timestamp?: ModelStringInput | null,
  screen_name?: ModelStringInput | null,
  source_device?: ModelStringInput | null,
  truncated?: ModelBooleanInput | null,
  user_status_count?: ModelIntInput | null,
  video_url?: ModelStringInput | null,
  configID?: ModelIDInput | null,
  and?: Array< ModelK24TweetsFilterInput | null > | null,
  or?: Array< ModelK24TweetsFilterInput | null > | null,
  not?: ModelK24TweetsFilterInput | null,
};

export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type CreateK24ConfigMutationVariables = {
  input: CreateK24ConfigInput,
  condition?: ModelK24ConfigConditionInput | null,
};

export type CreateK24ConfigMutation = {
  createK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateK24ConfigMutationVariables = {
  input: UpdateK24ConfigInput,
  condition?: ModelK24ConfigConditionInput | null,
};

export type UpdateK24ConfigMutation = {
  updateK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteK24ConfigMutationVariables = {
  input: DeleteK24ConfigInput,
  condition?: ModelK24ConfigConditionInput | null,
};

export type DeleteK24ConfigMutation = {
  deleteK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateK24TweetsMutationVariables = {
  input: CreateK24TweetsInput,
  condition?: ModelK24TweetsConditionInput | null,
};

export type CreateK24TweetsMutation = {
  createK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateK24TweetsMutationVariables = {
  input: UpdateK24TweetsInput,
  condition?: ModelK24TweetsConditionInput | null,
};

export type UpdateK24TweetsMutation = {
  updateK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteK24TweetsMutationVariables = {
  input: DeleteK24TweetsInput,
  condition?: ModelK24TweetsConditionInput | null,
};

export type DeleteK24TweetsMutation = {
  deleteK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetK24ConfigQueryVariables = {
  id: string,
};

export type GetK24ConfigQuery = {
  getK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListK24ConfigsQueryVariables = {
  filter?: ModelK24ConfigFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListK24ConfigsQuery = {
  listK24Configs:  {
    __typename: "ModelK24ConfigConnection",
    items:  Array< {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetK24TweetsQueryVariables = {
  id: string,
};

export type GetK24TweetsQuery = {
  getK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListK24TweetssQueryVariables = {
  filter?: ModelK24TweetsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListK24TweetssQuery = {
  listK24Tweetss:  {
    __typename: "ModelK24TweetsConnection",
    items:  Array< {
      __typename: "K24Tweets",
      id: string,
      Id: string,
      text: string,
      category: Category,
      tweet_created_at: string,
      tweet_date: string,
      user_name: string,
      topic: string,
      enabled: boolean | null,
      file_path: string,
      last_updated: string | null,
      duration_millis: number | null,
      favorite_count: number | null,
      followers_count: number | null,
      hashtags: Array< string | null > | null,
      location: string | null,
      media_url_https: string | null,
      reply_count: number | null,
      retweet_count: number | null,
      retweeted: boolean | null,
      row_timestamp: string | null,
      screen_name: string | null,
      source_device: string | null,
      truncated: boolean | null,
      user_status_count: number | null,
      video_url: string | null,
      configID: string,
      Config:  {
        __typename: "K24Config",
        id: string,
        name: string | null,
        category: Category,
        topic: string,
        query: string,
        enabled: boolean,
        file_path: string | null,
        last_updated: string | null,
        count: number,
        since_id: number | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ConfigByTopicQueryVariables = {
  topic?: string | null,
  category?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelK24ConfigFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ConfigByTopicQuery = {
  configByTopic:  {
    __typename: "ModelK24ConfigConnection",
    items:  Array< {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ConfigByCategoryQueryVariables = {
  category?: Category | null,
  topic?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelK24ConfigFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ConfigByCategoryQuery = {
  configByCategory:  {
    __typename: "ModelK24ConfigConnection",
    items:  Array< {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type TweetByTopicQueryVariables = {
  topic?: string | null,
  tweet_created_at?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelK24TweetsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type TweetByTopicQuery = {
  tweetByTopic:  {
    __typename: "ModelK24TweetsConnection",
    items:  Array< {
      __typename: "K24Tweets",
      id: string,
      Id: string,
      text: string,
      category: Category,
      tweet_created_at: string,
      tweet_date: string,
      user_name: string,
      topic: string,
      enabled: boolean | null,
      file_path: string,
      last_updated: string | null,
      duration_millis: number | null,
      favorite_count: number | null,
      followers_count: number | null,
      hashtags: Array< string | null > | null,
      location: string | null,
      media_url_https: string | null,
      reply_count: number | null,
      retweet_count: number | null,
      retweeted: boolean | null,
      row_timestamp: string | null,
      screen_name: string | null,
      source_device: string | null,
      truncated: boolean | null,
      user_status_count: number | null,
      video_url: string | null,
      configID: string,
      Config:  {
        __typename: "K24Config",
        id: string,
        name: string | null,
        category: Category,
        topic: string,
        query: string,
        enabled: boolean,
        file_path: string | null,
        last_updated: string | null,
        count: number,
        since_id: number | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type TweetByCategoryQueryVariables = {
  category?: Category | null,
  tweet_created_at?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelK24TweetsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type TweetByCategoryQuery = {
  tweetByCategory:  {
    __typename: "ModelK24TweetsConnection",
    items:  Array< {
      __typename: "K24Tweets",
      id: string,
      Id: string,
      text: string,
      category: Category,
      tweet_created_at: string,
      tweet_date: string,
      user_name: string,
      topic: string,
      enabled: boolean | null,
      file_path: string,
      last_updated: string | null,
      duration_millis: number | null,
      favorite_count: number | null,
      followers_count: number | null,
      hashtags: Array< string | null > | null,
      location: string | null,
      media_url_https: string | null,
      reply_count: number | null,
      retweet_count: number | null,
      retweeted: boolean | null,
      row_timestamp: string | null,
      screen_name: string | null,
      source_device: string | null,
      truncated: boolean | null,
      user_status_count: number | null,
      video_url: string | null,
      configID: string,
      Config:  {
        __typename: "K24Config",
        id: string,
        name: string | null,
        category: Category,
        topic: string,
        query: string,
        enabled: boolean,
        file_path: string | null,
        last_updated: string | null,
        count: number,
        since_id: number | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type TweetByUserQueryVariables = {
  user_name?: string | null,
  tweet_created_at?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelK24TweetsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type TweetByUserQuery = {
  tweetByUser:  {
    __typename: "ModelK24TweetsConnection",
    items:  Array< {
      __typename: "K24Tweets",
      id: string,
      Id: string,
      text: string,
      category: Category,
      tweet_created_at: string,
      tweet_date: string,
      user_name: string,
      topic: string,
      enabled: boolean | null,
      file_path: string,
      last_updated: string | null,
      duration_millis: number | null,
      favorite_count: number | null,
      followers_count: number | null,
      hashtags: Array< string | null > | null,
      location: string | null,
      media_url_https: string | null,
      reply_count: number | null,
      retweet_count: number | null,
      retweeted: boolean | null,
      row_timestamp: string | null,
      screen_name: string | null,
      source_device: string | null,
      truncated: boolean | null,
      user_status_count: number | null,
      video_url: string | null,
      configID: string,
      Config:  {
        __typename: "K24Config",
        id: string,
        name: string | null,
        category: Category,
        topic: string,
        query: string,
        enabled: boolean,
        file_path: string | null,
        last_updated: string | null,
        count: number,
        since_id: number | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type OnCreateK24ConfigSubscription = {
  onCreateK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateK24ConfigSubscription = {
  onUpdateK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteK24ConfigSubscription = {
  onDeleteK24Config:  {
    __typename: "K24Config",
    id: string,
    name: string | null,
    category: Category,
    topic: string,
    query: string,
    enabled: boolean,
    file_path: string | null,
    last_updated: string | null,
    count: number,
    since_id: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateK24TweetsSubscription = {
  onCreateK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateK24TweetsSubscription = {
  onUpdateK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteK24TweetsSubscription = {
  onDeleteK24Tweets:  {
    __typename: "K24Tweets",
    id: string,
    Id: string,
    text: string,
    category: Category,
    tweet_created_at: string,
    tweet_date: string,
    user_name: string,
    topic: string,
    enabled: boolean | null,
    file_path: string,
    last_updated: string | null,
    duration_millis: number | null,
    favorite_count: number | null,
    followers_count: number | null,
    hashtags: Array< string | null > | null,
    location: string | null,
    media_url_https: string | null,
    reply_count: number | null,
    retweet_count: number | null,
    retweeted: boolean | null,
    row_timestamp: string | null,
    screen_name: string | null,
    source_device: string | null,
    truncated: boolean | null,
    user_status_count: number | null,
    video_url: string | null,
    configID: string,
    Config:  {
      __typename: "K24Config",
      id: string,
      name: string | null,
      category: Category,
      topic: string,
      query: string,
      enabled: boolean,
      file_path: string | null,
      last_updated: string | null,
      count: number,
      since_id: number | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
